echo -e "[$(_c LIGHT_BLUE "Samba - Help")]"
echo -e "  $(_c CYAN "Commands:")"
echo -e "    $(_c LIGHT_CYAN "smb.add") - Add a Samba user (creates system user if needed)"
echo -e "    $(_c LIGHT_CYAN "smb.del") - Delete a Samba user (optionally remove system user)"
echo -e "    $(_c LIGHT_CYAN "smb.list") - List available Samba shares (use --short for brief output)"
echo -e "    $(_c LIGHT_CYAN "smb.restart") - Restart Samba service"
echo -e "    $(_c LIGHT_CYAN "smb.help") - Display this help message"
