echo -e "[$(_c LIGHT_BLUE "Docker - Help")]"
echo -e "  $(_c CYAN "Commands:")"
echo -e "    $(_c LIGHT_CYAN "d.attach") - Attach to a running container"
echo -e "    $(_c LIGHT_CYAN "d.exec") - Execute a command in a container"
echo -e "    $(_c LIGHT_CYAN "d.help") - Display this help message"
echo -e "    $(_c LIGHT_CYAN "d.inspect") - Inspect a container"
echo -e "      $(_c LIGHT_YELLOW "d.i") - Alias for $(_c LIGHT_CYAN "d.inspect")"
echo -e "    $(_c LIGHT_CYAN "d.list") - List all containers"
echo -e "      $(_c LIGHT_YELLOW "d.ls") - Alias for $(_c LIGHT_CYAN "d.list")"
echo -e "    $(_c LIGHT_CYAN "d.logs") - View logs of a container"
echo -e "      $(_c LIGHT_YELLOW "d.log") - Alias for $(_c LIGHT_CYAN "d.logs")"
echo -e "    $(_c LIGHT_CYAN "d.make-compose") - Generate a Docker Compose file"
echo -e "      $(_c LIGHT_YELLOW "d.mkc") - Alias for $(_c LIGHT_CYAN "d.make")"
echo -e "    $(_c LIGHT_CYAN "d.make-dockerfile") - Generate a Dockerfile"
echo -e "      $(_c LIGHT_YELLOW "d.mkd") - Alias for $(_c LIGHT_CYAN "d.make")"
echo -e "    $(_c LIGHT_CYAN "d.network") - Manage Docker networks"
echo -e "      $(_c LIGHT_YELLOW "d.net") - Alias for $(_c LIGHT_CYAN "d.network")"
echo -e "    $(_c LIGHT_CYAN "d.prune") - Prune unused Docker objects"
echo -e "    $(_c LIGHT_CYAN "d.remove") - Remove containers"
echo -e "      $(_c LIGHT_YELLOW "d.rm") - Alias for $(_c LIGHT_CYAN "d.remove")"
echo -e "    $(_c LIGHT_CYAN "d.restart") - Restart a container"
echo -e "    $(_c LIGHT_CYAN "d.shell") - Open a shell in a container"
echo -e "      $(_c LIGHT_YELLOW "d.sh") - Alias for $(_c LIGHT_CYAN "d.shell")"
echo -e "    $(_c LIGHT_CYAN "d.start") - Start a container"
echo -e "    $(_c LIGHT_CYAN "d.status") - Display stats of a container"
echo -e "      $(_c LIGHT_YELLOW "d.stat") - Alias for $(_c LIGHT_CYAN "d.status")"
echo -e "      $(_c LIGHT_YELLOW "d.stats") - Alias for $(_c LIGHT_CYAN "d.status")"
echo -e "    $(_c LIGHT_CYAN "d.stop") - Stop a container"
echo -e "    $(_c LIGHT_CYAN "d.updates") - List updates for running containers"
echo -e "    $(_c LIGHT_CYAN "d.up") - Start services with Docker Compose"
echo -e "  $(_c CYAN "Aliases:")"
echo -e "    $(_c LIGHT_CYAN "d") - Docker"
echo -e "    $(_c LIGHT_CYAN "dc") - Docker Compose"
