d.help() {
  printf "[$(_c LIGHT_BLUE "Docker - Help")] $(_c LIGHT_YELLOW "Usage: d.help <command>")\n"
  printf "  $(_c LIGHT_BLUE "Commands:")\n"
  printf "    $(_c LIGHT_BLUE "d.start") - Start a container\n"
  printf "    $(_c LIGHT_BLUE "d.restart") - Restart a container\n"
  printf "    $(_c LIGHT_BLUE "d.stop") - Stop a container\n"
  printf "    $(_c LIGHT_BLUE "d.shell") - Open a shell in a container\n"
  printf "    $(_c LIGHT_BLUE "d.logs") - View logs of a container\n"
  printf "    $(_c LIGHT_BLUE "d.list") - List all containers\n"
  printf "    $(_c LIGHT_BLUE "d.stats") - Display stats of a container\n"
  printf "    $(_c LIGHT_BLUE "d.help") - Display this help message\n"
  printf "  $(_c LIGHT_BLUE "Aliases:")\n"
  printf "    $(_c LIGHT_BLUE "d") - Docker\n"
  printf "    $(_c LIGHT_BLUE "dc") - Docker Compose\n"
}
