#!/bin/bash

d.help() {
  __epx_echo "[$(_c LIGHT_BLUE "Docker - Help")]"
  __epx_echo "  $(_c CYAN "Commands:")"
  __epx_echo "    $(_c LIGHT_CYAN "d.attach") - Attach to a running container"
  __epx_echo "    $(_c LIGHT_CYAN "d.compose") - Docker Compose commands"
  __epx_echo "    $(_c LIGHT_CYAN "d.exec") - Execute a command in a container"
  __epx_echo "    $(_c LIGHT_CYAN "d.help") - Display this help message"
  __epx_echo "    $(_c LIGHT_CYAN "d.inspect") - Inspect a container or image"
  __epx_echo "    $(_c LIGHT_CYAN "d.list") - List all containers"
  __epx_echo "    $(_c LIGHT_CYAN "d.logs") - View logs of a container"
  __epx_echo "    $(_c LIGHT_CYAN "d.make") - Build images or containers"
  __epx_echo "    $(_c LIGHT_CYAN "d.network") - Manage Docker networks"
  __epx_echo "    $(_c LIGHT_CYAN "d.prune") - Prune unused Docker objects"
  __epx_echo "    $(_c LIGHT_CYAN "d.remove") - Remove containers or images"
  __epx_echo "    $(_c LIGHT_CYAN "d.restart") - Restart a container"
  __epx_echo "    $(_c LIGHT_CYAN "d.shell") - Open a shell in a container"
  __epx_echo "    $(_c LIGHT_CYAN "d.start") - Start a container"
  __epx_echo "    $(_c LIGHT_CYAN "d.stats") - Display stats of a container"
  __epx_echo "    $(_c LIGHT_CYAN "d.stop") - Stop a container"
  __epx_echo "    $(_c LIGHT_CYAN "d.up") - Start services with Docker Compose"
  __epx_echo "  $(_c CYAN "Aliases:")"
  __epx_echo "    $(_c LIGHT_CYAN "d") - Docker"
  __epx_echo "    $(_c LIGHT_CYAN "dc") - Docker Compose"
}
