source "${EPX_HOME}/helpers/header.sh"

source "${EPX_HOME}/helpers/colorize.sh"
source "${EPX_HOME}/helpers/colors.sh"

echo -e "[$(_c LIGHT_BLUE "Common - Help")]"
echo -e "  $(_c CYAN "Commands:")"
echo -e "    $(_c LIGHT_CYAN "archive") - Archive files or directories"
echo -e "    $(_c LIGHT_CYAN "unarchive") - Unarchive files or directories"
echo -e "    $(_c LIGHT_CYAN "zst") - Zstandard ultra compression command"
echo -e "    $(_c LIGHT_CYAN "zst-lite") - Zstandard compression command"
echo -e "    $(_c LIGHT_CYAN "unzst") - Zstandard decompression command"
echo -e "    $(_c LIGHT_CYAN "copy") - Copy files or directories"
echo -e "    $(_c LIGHT_CYAN "move") - Move files or directories"
echo -e "    $(_c LIGHT_CYAN "rmt") - Move files or directories to trash with progress indication"
echo -e "    $(_c LIGHT_CYAN "rmp") - Remove files or directories with progress indication"
echo -e "    $(_c LIGHT_CYAN "freeze") - Make files/directories append-only (immutable)"
echo -e "    $(_c LIGHT_CYAN "unfreeze") - Remove append-only attribute from files/directories"
echo -e "    $(_c LIGHT_CYAN "lock") - Make files/directories immutable (read-only)"
echo -e "    $(_c LIGHT_CYAN "unlock") - Remove immutable attribute from files/directories"
echo -e "    $(_c LIGHT_CYAN "ff") - Display system information with fastfetch"
echo -e "    $(_c LIGHT_CYAN "gtop") - Display GPU information with nvidia-smi"
echo -e "    $(_c LIGHT_CYAN "ls") - Enhanced directory listing with eza/exa or fallback to ls"
echo -e "    $(_c LIGHT_CYAN "du-all") - Docker update all containers"
echo -e "    $(_c LIGHT_CYAN "dcu") - Docker Compose up command"
