echo -e "[$(_c LIGHT_BLUE "Common - Help")]"
echo -e "  $(_c CYAN "Commands:")"
echo -e "    $(_c LIGHT_CYAN "c.help") - Display this help message"
echo -e "    $(_c LIGHT_CYAN "c") - Clear the terminal"
echo -e "    $(_c LIGHT_CYAN "dcu") - Docker Compose up command"
echo -e "    $(_c LIGHT_CYAN "du-all") - Docker update all containers"
echo -e "    $(_c LIGHT_CYAN "ff") - Display system information with fastfetch"
echo -e "    $(_c LIGHT_CYAN "gtop") - Display GPU information with nvidia-smi"
echo -e "    $(_c LIGHT_CYAN "lse") - Enhanced directory listing with eza/exa or fallback to ls"
echo -e "    $(_c LIGHT_CYAN "lsp") - Enhanced directory listing with eza/exa with permissions or fallback to ls"
