echo -e "[$(_c LIGHT_BLUE "FileSystem - Help")]"
echo -e "  $(_c CYAN "Commands:")"
echo -e "    $(_c LIGHT_CYAN "fs.help") - Display this help message"
echo -e "    $(_c LIGHT_CYAN "fs.archive") - Archive files or directories"
echo -e "    $(_c LIGHT_CYAN "fs.unarchive") - Unarchive files or directories"
echo -e "    $(_c LIGHT_CYAN "fs.zst") - Zstandard ultra compression command"
echo -e "    $(_c LIGHT_CYAN "fs.zst-lite") - Zstandard compression command"
echo -e "    $(_c LIGHT_CYAN "fs.unzst") - Zstandard decompression command"
echo -e "    $(_c LIGHT_CYAN "fs.7z") - 7zip compression command"
echo -e "    $(_c LIGHT_CYAN "fs.un7z") - 7zip decompression command"
echo -e "    $(_c LIGHT_CYAN "fs.disk") - Display disk usage information"
echo -e "    $(_c LIGHT_CYAN "fs.mkdummy") - Create a dummy file with specified size"
echo -e "  $(_c CYAN "Aliases:")"
echo -e "    $(_c LIGHT_CYAN "fs.bak") - (fs.archive) Archive files or directories"
echo -e "    $(_c LIGHT_CYAN "fs.unbak") - (fs.unarchive) Unarchive files or directories"
echo -e "    $(_c LIGHT_CYAN "fs.lock") - (chattr +i) Make files/directories immutable (read-only)"
echo -e "    $(_c LIGHT_CYAN "fs.unlock") - (chattr -i) Remove immutable attribute from files/directories"
echo -e "    $(_c LIGHT_CYAN "fs.freeze") - (chattr +a) Make files/directories append-only (immutable)"
echo -e "    $(_c LIGHT_CYAN "fs.unfreeze") - (chattr -a) Remove append-only attribute from files/directories"
echo -e "    $(_c LIGHT_CYAN "fs.rm") - (rm -rfvI) Remove files or directories with confirmation and verbose output"
echo -e "    $(_c LIGHT_CYAN "fs.cp") - (cp -rfvi --update=all) Copy files or directories with confirmation, verbose output, and only if source is newer"
echo -e "    $(_c LIGHT_CYAN "fs.copy") - (cp -rfvi --update=all) Copy files or directories with confirmation, verbose output, and only if source is newer"
echo -e "    $(_c LIGHT_CYAN "fs.mv") - (mv -fvi --update=all) Move files or directories with confirmation, verbose output, and only if source is newer"
echo -e "    $(_c LIGHT_CYAN "fs.move") - (mv -fvi --update=all) Move files or directories with confirmation, verbose output, and only if source is newer"
echo -e "    $(_c LIGHT_CYAN "fs.own") - (chown -R) Change ownership of files or directories recursively"
echo -e "    $(_c LIGHT_CYAN "fs.mod") - (chmod -R) Change permissions of files or directories recursively"
echo -e "    $(_c LIGHT_CYAN "fs.size") - (du -sh) Display size of files or directories in human-readable format"
