echo -e "[$(_c LIGHT_BLUE "Minecraft - Help")]"
echo -e "  $(_c CYAN "Commands:")"
echo -e "    $(_c LIGHT_CYAN "mc.add") - Create a new Minecraft server instance"
echo -e "    $(_c LIGHT_CYAN "mc.attach") - Attach to a running Minecraft server console"
echo -e "    $(_c LIGHT_CYAN "mc.install") - Install the Minecraft server project"
echo -e "    $(_c LIGHT_CYAN "mc.list") - List all Minecraft server instances"
echo -e "    $(_c LIGHT_CYAN "mc.log") - View logs of a Minecraft server"
echo -e "    $(_c LIGHT_CYAN "mc.ls") - List running Minecraft containers"
echo -e "    $(_c LIGHT_CYAN "mc.restart") - Restart a Minecraft server"
echo -e "    $(_c LIGHT_CYAN "mc.rm") - Remove a Minecraft server container"
echo -e "    $(_c LIGHT_CYAN "mc.shell") - Open a shell in a Minecraft server container"
echo -e "    $(_c LIGHT_CYAN "mc.start") - Start a Minecraft server"
echo -e "    $(_c LIGHT_CYAN "mc.stop") - Stop a running Minecraft server"
echo -e "    $(_c LIGHT_CYAN "mc.update") - Update the Minecraft server project"
echo -e "    $(_c LIGHT_CYAN "mc.help") - Display this help message"

