echo -e "[$(_c LIGHT_BLUE "Python - Help")]"
echo -e "  $(_c CYAN "Commands:")"
echo -e "    $(_c LIGHT_CYAN "py.create") - Create a new Python project or environment"
echo -e "    $(_c LIGHT_CYAN "py.install") - Install Python packages"
echo -e "      $(_c LIGHT_YELLOW "py.i") - Alternative command for $(_c LIGHT_CYAN "py.install")"
echo -e "      $(_c LIGHT_YELLOW "py.add") - Alternative command for $(_c LIGHT_CYAN "py.install")"
echo -e "    $(_c LIGHT_CYAN "py.pm2") - Manage Python processes with PM2"
echo -e "    $(_c LIGHT_CYAN "py.uninstall") - Remove Python packages or environments"
echo -e "      $(_c LIGHT_YELLOW "py.rm") - Alternative command for $(_c LIGHT_CYAN "py.uninstall")"
echo -e "      $(_c LIGHT_YELLOW "py.remove") - Alternative command for $(_c LIGHT_CYAN "py.uninstall")"
echo -e "    $(_c LIGHT_CYAN "py.venv") - Manage Python virtual environments"
echo -e "      $(_c LIGHT_YELLOW "py.env") - Alternative command for $(_c LIGHT_CYAN "py.venv")"
echo -e "    $(_c LIGHT_CYAN "py.help") - Display this help message"
echo -e "  $(_c CYAN "Aliases:")"
echo -e "    $(_c LIGHT_CYAN "py") - Python"
echo -e "    $(_c LIGHT_CYAN "py3") - Python3"
