echo -e "[$(_c LIGHT_BLUE "IT - Help")]"
echo -e "  $(_c CYAN "Commands:")"
echo -e "    $(_c LIGHT_CYAN "it.b64") - Encode or decode Base64 strings"
echo -e "    $(_c LIGHT_CYAN "it.rnd-string") - Generate random strings of specified length"
echo -e "    $(_c LIGHT_CYAN "it.rnd-number") - Generate random numbers within a specified range"
echo -e "    $(_c LIGHT_CYAN "it.rnd-port") - Find an available random port on the system"
echo -e "    $(_c LIGHT_CYAN "it.uuid") - Generate UUIDs of specified version"
echo -e "    $(_c LIGHT_CYAN "it.hash") - Generate hashes (MD5, SHA1, SHA256, SHA512) for a given string or file"
echo -e "    $(_c LIGHT_CYAN "it.hmac") - Generate HMAC hashes (MD5, SHA1, SHA256, SHA512) for a given string or file using a secret key"
echo -e "    $(_c LIGHT_CYAN "it.qr") - Generate QR codes from text or URLs"
echo -e "    $(_c LIGHT_CYAN "it.qr-wifi") - Generate WiFi QR codes for easy network connection"
echo -e "    $(_c LIGHT_CYAN "it.barcode") - Generate barcodes from text or numbers"
echo -e "    $(_c LIGHT_CYAN "it.timestamp") - Convert between human-readable dates and Unix timestamps"
echo -e "    $(_c LIGHT_CYAN "it.timezone") - Display current time in different time zones"
echo -e "    $(_c LIGHT_CYAN "it.ipinfo") - Retrieve information about an IP address"
echo -e "    $(_c LIGHT_CYAN "it.useragent") - Parse and display information from a user-agent string"
echo -e "    $(_c LIGHT_CYAN "it.urlencode") - URL encode or decode strings"
echo -e "    $(_c LIGHT_CYAN "it.htmlencode") - HTML encode or decode strings"
echo -e "    $(_c LIGHT_CYAN "it.regex-test") - Test if a string matches a given regular expression"
echo -e "    $(_c LIGHT_CYAN "it.regex-extract") - Extract substrings from a string using a regular expression"
